import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "KnowledgeOS — Enterprise AI Knowledge Platform",
  description: "KnowledgeOS public sample-document prototype and proposed enterprise architecture. Private ingestion and organization workspaces are in development.",
  alternates: { canonical: "/knowledgeos/enterprise" },
};

const linkedin="https://www.linkedin.com/company/knowledgeos-ai";

export default function EnterpriseKnowledgeOS(){
 const useCases=[
  ["Employee enablement","Give teams one place to ask HR, policy, process and operational questions with source evidence."],
  ["Sales & revenue","Ground reps in approved product, qualification, pricing-process and implementation knowledge."],
  ["Customer operations","Help support and success teams retrieve approved procedures before responding to customers."],
  ["Implementation teams","Surface requirements, handoff notes, UAT standards and launch procedures without hunting through folders."],
 ];
 return <main className="min-h-screen bg-[#0a0d10] text-white">
  <header className="border-b border-white/10"><div className="mx-auto flex max-w-[1380px] items-center justify-between px-6 py-5"><Link href="/knowledgeos/enterprise" className="text-xl font-black tracking-[-.03em]">KnowledgeOS</Link><nav className="flex items-center gap-6 text-sm text-white/70"><a href="#platform">Platform</a><a href="#security">Security</a><a href="#use-cases">Use cases</a><Link href="/knowledgeos" className="border border-white/25 px-4 py-2 text-white">Live demo</Link></nav></div></header>
  <section className="mx-auto max-w-[1380px] px-6 pb-20 pt-20 lg:pb-28 lg:pt-28">
   <div className="grid gap-14 lg:grid-cols-[1.05fr_.95fr] lg:items-end">
    <div><div className="text-sm font-bold uppercase tracking-[.2em] text-[#c8ff55]">Enterprise concept · Public prototype</div><h1 className="mt-6 max-w-[12ch] text-[clamp(54px,7vw,104px)] font-black leading-[.88] tracking-[-.055em]">Your company already knows the answer.</h1><p className="mt-7 max-w-[58ch] text-xl leading-8 text-white/65">The public KnowledgeOS prototype retrieves labeled sample documents, answers from their evidence, and shows citations. Private document ingestion, authenticated organization workspaces, and permission-aware retrieval are in development, not available in this demo.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/knowledgeos/demo" className="bg-[#c8ff55] px-6 py-4 font-bold text-black">Discuss an enterprise pilot →</Link><Link href="/knowledgeos" className="border border-white/25 px-6 py-4 font-bold">Try the public prototype</Link></div></div>
    <div className="border border-white/15 bg-[#11161b] p-7"><div className="text-xs uppercase tracking-[.18em] text-white/40">How KnowledgeOS answers</div>{[["01","Retrieve","Find the most relevant approved knowledge."],["02","Ground","Give the model evidence before it generates."],["03","Answer","Respond with visible source citations."],["04","Control","Refuse when the evidence cannot support an answer."]].map(([n,h,t])=><div key={n} className="grid grid-cols-[44px_110px_1fr] gap-4 border-b border-white/10 py-5 last:border-0"><span className="font-mono text-white/35">{n}</span><b>{h}</b><span className="text-white/55">{t}</span></div>)}</div>
   </div>
  </section>
  <section id="platform" className="border-y border-white/10 bg-[#f0eee7] text-black"><div className="mx-auto max-w-[1380px] px-6 py-20"><p className="text-sm font-bold uppercase tracking-[.18em]">Proposed enterprise architecture</p><h2 className="mt-4 max-w-[18ch] text-[clamp(40px,5vw,72px)] font-black leading-[.95] tracking-[-.045em]">An answer layer over the knowledge your business already owns.</h2><div className="mt-14 grid gap-px border border-black/20 bg-black/20 md:grid-cols-3">{[["Knowledge ingestion","Planned: approved policies, playbooks, SOPs and operational documents."],["Evidence-aware retrieval","The public prototype ranks evidence from its fixed sample corpus."],["Grounded answers","The prototype returns citations or an unsupported-answer state."],["Access boundaries","Planned: authenticated organization workspaces and tested row-level permissions."],["Admin & evaluation","Planned: persisted indexing, re-indexing, auditability and monitoring."],["Integration-ready","Proposed: approved internal-tool and CRM integrations after scoped validation."]].map(([h,t])=><article key={h} className="bg-[#f0eee7] p-7"><h3 className="text-xl font-bold">{h}</h3><p className="mt-3 leading-7 text-black/60">{t}</p></article>)}</div></div></section>
  <section id="use-cases" className="mx-auto max-w-[1380px] px-6 py-20"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#c8ff55]">Use cases</p><h2 className="mt-4 text-5xl font-black tracking-[-.04em]">One knowledge layer. Multiple teams.</h2></div><div>{useCases.map(([h,t])=><article key={h} className="grid gap-3 border-t border-white/15 py-7 md:grid-cols-[200px_1fr]"><h3 className="font-bold">{h}</h3><p className="text-white/60">{t}</p></article>)}</div></div></section>
  <section id="security" className="border-y border-white/10 bg-[#11161b]"><div className="mx-auto grid max-w-[1380px] gap-12 px-6 py-20 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#c8ff55]">Enterprise architecture</p><h2 className="mt-4 text-5xl font-black tracking-[-.04em]">Designed around evidence, permissions and operational control.</h2><p className="mt-6 max-w-[58ch] leading-7 text-white/60">The current public demonstration uses synthetic knowledge. Enterprise deployments are scoped around the customer&apos;s identity model, data boundaries, approved sources, retention requirements, model provider and integration environment.</p></div><div className="grid gap-4 text-sm">{["Server-side model credentials","Permission-aware retrieval design","Source-level evidence returned with answers","Explicit unsupported-answer behavior","Human-controlled source ingestion and re-indexing","Evaluation for retrieval, groundedness, citations and latency"].map(x=><div key={x} className="border-b border-white/15 py-4 font-semibold">{x}</div>)}</div></div></section>
  <section className="mx-auto max-w-[1380px] px-6 py-20"><div className="grid gap-8 lg:grid-cols-3"><div><p className="text-sm uppercase tracking-[.18em] text-white/40">Pilot</p><h3 className="mt-2 text-2xl font-bold">Department deployment</h3><p className="mt-3 text-white/55">Validate priority knowledge, user workflows, answer quality and governance with one defined team.</p></div><div><p className="text-sm uppercase tracking-[.18em] text-white/40">Enterprise</p><h3 className="mt-2 text-2xl font-bold">Multi-team knowledge layer</h3><p className="mt-3 text-white/55">Expand sources, permissions, integrations and evaluation around your operating environment.</p></div><div><p className="text-sm uppercase tracking-[.18em] text-white/40">Commercial model</p><h3 className="mt-2 text-2xl font-bold">Scoped after discovery</h3><p className="mt-3 text-white/55">Pricing depends on users, source volume, security requirements, integrations, model usage and deployment scope.</p></div></div></section>
  <section className="bg-[#c8ff55] text-black"><div className="mx-auto grid max-w-[1380px] gap-8 px-6 py-16 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-sm font-bold uppercase tracking-[.18em]">See it with your workflow</p><h2 className="mt-3 max-w-[18ch] text-5xl font-black tracking-[-.045em]">Bring one knowledge problem. We&apos;ll map the implementation.</h2></div><div className="flex flex-wrap gap-3"><Link href="/knowledgeos/demo" className="bg-black px-6 py-4 font-bold text-white">Request a demo →</Link><Link href="/work/knowledgeos" className="border border-black px-6 py-4 font-bold">Review implementation</Link></div></div></section>
 </main>
}
